settings:
  legacy:
    force: false
    interval: 2s
server:
  status: true
  open: false
  port: 5002
  host: 0.0.0.0
schema:
- name: myddns-app
  path: .
  commands:
    vet:
      status: true
    install:
      status: true
      method: go build -o app
    run:
      status: true
      method: ./app
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
